### PR TITLE
dws: start epilog on finish event

### LINKED ISSUE #472: Too many nodes drained on elcap with message "failed to unmount rabbit"
@kkier reported that 4k and then later 11k jobs were drained with the message. The message comes from one place, line 401 in /bin/coral2_dws.py. The function is pretty simple: ask kubernetes for all nodes in the job that do not report themselves as being in the Unmounted state, and drain them.

The function is called if a workflow has been in postrun for longer than the configured timeout, which is 15 minutes on elcap.

### PR DESCRIPTION
**Pull request by jameshcorbett**
@grondo asked in #472 

> Why is the dws epilog action started on entry to CLEANUP state instead of on the finish event?
> 
> As noted above, the job-manager.epilog doesn't start until the finish event. Would it make sense to start the dws epilog at the same time (along with the timer)? Before the finish event is posted, there are still IMP, job shell, and maybe user processes on one or more nodes of the job, so it may not make sense to do whatever occurs in the DWS epilog action.
> 
> A case to handle here though is when a prolog fails there will be no start event and thus no finish event. In the perilog plugin the job-manager.epilog is started immediately when the job-manager.prolog fails. The dws jobtap plugin could handle this case by starting its epilog action on entry to the CLEANUP state when there was no start event (using flux_jobtap_job_event_posted()).

He made a good point. 

Fixes #472.

### CODE REVIEW

File: src/job-manager/plugins/dws-jobtap.c [hunk 1]
```diff
@@ -444,17 +444,91 @@ static void epilog_timeout_cb (flux_reactor_t *r, flux_watcher_t *w, int revents
...
     struct create_arg_t *create_args = NULL;
 
+    if (!r) {
+        flux_log_error (h, "Failed to fetch reactor from handle for %s", idf58 (id));
+        current_job_exception (p, "Failed to fetch reactor from handle");
+        return -1;
+    }
+    if (!(create_args = calloc (1, sizeof (struct create_arg_t)))
+        || flux_jobtap_job_aux_set (p, FLUX_JOBTAP_CURRENT_JOB, NULL, create_args, free) < 0) {
+        free (create_args);
```
Comment (garlick) [inline src/job-manager/plugins/dws-jobtap.c]: free clobbers errno

**Review by garlick — APPROVED** [review]
This looks good to me, but no tests?

**Comment by jameshcorbett** [comment]
> This looks good to me, but no tests?

Hmmm, well it passing the existing test suite is a lot, because the behavior is supposed to be the almost identical. The only time the new behavior would differ from the old would be if there were a stuck process or something, so the `finish` event were not posted for a while. But I added some tests regardless.
